### PR TITLE
feat(highlights): basic highlights for Aerial support

### PR DESCRIPTION
**Pull request by windowsrefund**
Very basic but looks good on my end.

### CODE REVIEW

**Comment by ramojus** [comment]
Thanks. This plugin will take up a lot of UI, so I think we should create some config for this one. Something general like symbols_outline, so that other similar plugins can use the same config if needed.
Default could be:
```lua
{
    transparent_background = {
        symbols_outline = true
    },
    flat_background = {
        symbols_outline = false
    },
}
```
So by default it would have the same (darker) background as file-tree and LineNr

**Comment by ramojus** [comment]
I just checked and they don't seem to have a way to set background for the whole window...
Then the config stays unchaged I guess, but this could be a todo for the future if they ever support it.

This looked a bit better for me:
```lua
    hl.set("AerialNormal", { fg = colors.fg2 })
    hl.set("AerialLine", { fg = colors.fg, bg = colors.bg4 })
    hl.set("AerialLineNC", { fg = colors.fg2, bg = colors.bg3 })
```
I've looked at some other places where a line is selected in this colorscheme (pmenu, telescope) and non-neutral color for fg is never used, only brighter bg if needed, so I think this is more in line with the colorscheme style.

**Comment by windowsrefund** [comment]
Glad a config wasn't needed as I have no idea what that would have meant. Thanks for the help. Looks great!

**Comment by ramojus** [comment]
It really is much easier than it may sound like :) file-tree plugins could be used as a reference
Also next time, there's no need to manually edit doc/mellifluous.txt, it get's updated automatically from readme with a github workflow (using [panvimdoc](https://github.com/kdheepak/panvimdoc)). So just pushing changed readme is enough.

**Pull request merged**
